V2
kompotik/ko3 pull request #2
Opened 2017-03-30 08:09 UTC by KonstantinZv

2017-05-22 09:58 UTC, sotnikov-link requested changes
Отличная вёрстка!

Выявил одно мелкое, но существенное замечание «541 px»:
<img width="633" alt="2017-05-22 10 06 29" src="https://cloud.githubusercontent.com/assets/10273334/26296372/1b3fd332-3ed7-11e7-9be7-f6b424cd3d6e.png">

Подумай, как должно быть правильно 😃

***

Ещё заметил мелочь, оказалось у Светы тоже есть:
<img width="509" alt="2017-05-22 10 05 48" src="https://cloud.githubusercontent.com/assets/10273334/26296433/58e5b918-3ed7-11e7-956b-6ef4ae4f98f2.png">

На один пиксель в право надо переместить нижний блок, который с кнопками для соц. сетей. Это замечание можно не исправлять, если замучился 🍭

2017-05-26 07:50 UTC, KonstantinZv commented
Я как раз и пытался не допустить отступа в один пиксель (замечание №2 в пулл-реквесте), поэтому и общая ширина умышленно выбрана 541 пиксель а не 540 пикселей (замечание №1 в пулл-реквесте). 
![image](https://cloud.githubusercontent.com/assets/25768165/26485662/90162298-4200-11e7-97c3-34c1521bc7b0.png)
Поэтому, прежде чем править, хочу обсудить этот момент)

2017-05-26 15:51 UTC, sotnikov-link commented
541 пиксель выставлять — точно не вариант. Если уж «системно» стоит 540 у всех, то ради того, что ты не можешь прижать соц-кнопки правее на один пиксель, отходить от «системы» явно не стоит. Лучше принять не прижатые соц-кнопки, чем в одном месте вставлять 541, никому не будет ясен такой код в будущем, если его кто-то будет смотреть.

Ты ведь можешь выставить 540 пикселей и сделать отступы в таблице у ячеек при помощи паддингов.

2017-06-01 17:02 UTC, sotnikov-link commented
Не надо было создавать отдельный пул-реквест (https://github.com/kompotik/ko3/pull/3) — так проверять не удобно. Перетащил изменения из той ветки в эту.

2017-06-01 17:03 UTC, sotnikov-link approved these changes

2017-06-01 17:03 UTC, merged